import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import "./styles/styles.scss";

import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({
  subsets: ["latin"], // required
  weight: ["300", "400", "500", "700"], // optional: choose your weights
  display: "swap", // optional: reduces layout shift
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
